type: task
# The name is optional, if not specified, generated randomly
name: susu-train-001

# Using the official Axolotl's Docker image
image: winglian/axolotl-cloud:main-20240429-py3.11-cu121-2.2.1

# Required environment variables
env:
  - HUGGING_FACE_HUB_TOKEN
  - WANDB_API_KEY
# Commands of the task
commands:
  - accelerate launch -m axolotl.cli.train axolotl/config.yaml

resources:
  gpu:
    # 24GB or more vRAM
    memory: 62GB
    # Two or more GPU
    count: 1..
